### ISSUE TITLE
对于create接口 要怎么进行压测呢

### ISSUE THREAD

**Issue by sprayerH** [link1st/go-stress-testing#100]
这里的create接口指带有副作用，需要每次请求都传递不同的参数，比如creatUser这种，用户名需要不同。
这种情况要怎么测试呢，萌新不懂，请教一下

**Comment by link1st** [comment]
压测脚本启动的时候，可以设置一些默认参数如 压测接口、压测时间等，所以只能压测一些接口参数不用修改的服务

如果压测 create 接口可以使用:
1、修改服务端代码，userName 可以由服务端随机，不使用客户端传递参数
2、修改项目源码，添加随机函数 每次 userName 都随机生成。
