### ISSUE TITLE
如何进行可变参数压测

### ISSUE THREAD

**Issue by lscool66** [link1st/go-stress-testing#102]
如数字参数，token参数等

**Comment by hzh-test** [comment]
同问，没有这功能还不如直接自己写个 go 脚本

**Comment by link1st** [comment]
压测执行的时候就需要传入参数，如果是可变参数 参数是如何进行随机、需要更新哪些字段，这些都是不确定的。
与其用很复杂的方式进行压测，还不如使得压测工具简单的，可以用很简短的命令就可以进行接口。

关于可变参数的解决方案:
1、关于断言分步压测 [issues/79](https://github.com/link1st/go-stress-testing/issues/79)
2、在每次发送请求调用的函数，添加需要随机函数控制参数
https://github.com/link1st/go-stress-testing/blob/d72acfeea411efb1208754d829f620366ccf2dbe/server/golink/http_link.go#L60~L81
3、修改服务端，在服务端生成随机参数
