### ISSUE TITLE
qps为什么要乘协程数

### ISSUE THREAD

**Issue by 89trillion-liheqian** [link1st/go-stress-testing#104]
![截屏2022-09-23 18 26 20](https://user-images.githubusercontent.com/85985369/191941668-d43c18ab-a9f2-4530-8512-369c94c70cce.png)

这里successNum不是已经是总数了嘛，是不是算错了

**Comment by link1st** [comment]
可以查看一下这个 issues 
https://github.com/link1st/go-stress-testing/issues/26

**Comment by biningo** [comment]
QPS计算已经不用乘上并发数了吧，已经看过这个里面的分析了，可是ch里面的successNum已经是全部并发请求成功的数量了，QPS=全部请求成功数量/总耗时

**Comment by biningo** [comment]
> QPS计算已经不用乘上并发数了吧，已经看过这个里面的分析了：#26 ，可是ch里面的successNum已经是全部并发请求成功的数量了，QPS=全部请求成功数量/总耗时

我知道了，processingTime是多个并发下每个请求的响应延时之和，所以这里`QPS=successNum*concurrency/processingTime`和 `QPS=successNum/requestTime` 算出来的值是差不多的
