### ISSUE TITLE
为什么有时候统计结果像是被卡住了一样

### ISSUE THREAD

**Issue by RuiJie-Mr** [link1st/go-stress-testing#105]
![image](https://user-images.githubusercontent.com/71678528/195035510-65712e85-8e2a-41e2-879a-7c8561020e79.png)
这段时间内因为一个请求的失败导致所有的数据都停止更新了，包括成功数、失败数、qps等，好像是所有的goroutine都被卡住了一样，想问问大佬是怎么回事？

**Comment by link1st** [comment]
-c 100 是启动 100个协程
-n 1000 是每个协程执行次数

看你这个现象是，约 99个协程都处理完成了，分别完成了1000 次请求，只有一个协程在请求的时候卡住了  所以会显示 成功数一直在 99723 不动，当这个请求超时的时候 又会正常请求

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/12679836/195054411-cd401de0-16d1-4e59-8440-a8eaf4020c28.png">
