### ISSUE TITLE
想请教一下，这种压测工具设计，是不是要用到http连接池？

### ISSUE THREAD

**Issue by VanLiuZhi** [link1st/go-stress-testing#109]
如题，我理解的就是，如果有一个http工具库，就可以发起http请求，但是一直发起新请求，最终肯定会耗尽客户端tcp连接的，是不是要用连接池来解决这种问题？

如果大量的请求处理都是长事务，就是返回很慢，即使使用连接池，也会出现耗尽tcp连接的情况(当然这种情况很极限吧)

**Comment by link1st** [comment]
线上用户每次都是不同的设备，每次调用都会创建一个新的连接，本项目默认是不使用连接池，尽量模拟线上真实用户场景。
每次调用都会 tcp 三次握手，建立连接，发送数据，这样会消耗客户端 连接句柄数，所以对压测客户端要求比较高

[客户端性能优化](https://github.com/link1st/go-stress-testing#62-%E5%86%85%E6%A0%B8%E4%BC%98%E5%8C%96) 端口快速回收、增大连接句柄数等来避免这个问题。
> 最终肯定会耗尽客户端tcp连接的

本项目支持 keep alive ，多次调用 HTTP API 复用同一个 http client。使用连接池 
`keepalive          = false   // 是否开启长连接`
