### ISSUE TITLE
postman导出的curl请求无法用

### ISSUE THREAD

**Issue by zhangya4548** [link1st/go-stress-testing#11]
postman导出的curl请求代码无法用,测试了后才发现是curl格式你好像只支持浏览器复制的curl格式,

建议兼容postman导出的curl格式,谢谢

**Comment by zhangya4548** [comment]
对了我是postman导出post的curl格式保存文件后,然后 -d 的参数使用的

**Comment by link1st** [comment]
好的，我试着看一下 postman 的 curl 格式，看看能否兼容一下
