### ISSUE TITLE
怎么对有多个接口的流程压测，能出个文档吗？

### ISSUE THREAD

**Issue by yingjie52** [link1st/go-stress-testing#114]
怎么对有多个接口的流程压测，能出个文档吗？

**Comment by link1st** [comment]
多个接口压测，涉及每个接口都有不同的权重，只能修改代码重新编译才能完成

参考链接:
[分步压测示例代码](https://github.com/link1st/go-stress-testing/blob/master/server/golink/http_link_many.go) 
[加权压测示例代码](https://github.com/link1st/go-stress-testing/blob/master/server/golink/http_link_weigh.go)
