### ISSUE TITLE
发起websocket为什么需要暂停？而且暂停时间是1秒写的60秒

### ISSUE THREAD

**Issue by yyltesting** [link1st/go-stress-testing#119]
![image](https://user-images.githubusercontent.com/49899832/222100854-c4b621aa-2702-4094-b17f-7357cea79529.png)

**Comment by link1st** [comment]
注释没有及时更新，我更新一下注释说明

**Comment by link1st** [comment]
webScoket 压测有两种方式，一种是压测最大连接数，本项目就是这种，所以每个连接建立连接以后会发送一条消息，然后保持连接不断
还有一种建立 tcp 通讯以后，压测 QPS，这种则需要收到回复的消息以后就立即发送消息，则需要取消定时器功能
