### ISSUE TITLE
并发超过7000就会报错 “net/http: request canceled (Client.Timeout exceeded while awaiting headers)”

### ISSUE THREAD

**Issue by hgkiller** [link1st/go-stress-testing#12]
使用压测时，使用命令“./go-stress-testing-linux  -c  7500 -n 1 -u http://www.test1111.com”
此时会报错，
“请求失败: Get http://www.test1111.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
请求失败: Get http://www.test1111.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
请求失败: Get http://www.test1111.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
请求失败: Get http://www.test1111.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
请求失败: Get http://www.test1111.com: net/http: request canceled (Client.Timeout exceeded while awaiting headers)”

**Comment by link1st** [comment]
在压测http接口的时候的时候，需要先连接服务器才能进行接口压测
在建立连接的时候就会收到一些限制，如本地的端口不够用、网络带宽的显示、服务压力压力过大

一般设置并发数过大，是带宽不够 
1、建议使用内网、或者是同一台机器进行压测
2、是将并发数设置的小一点
3、是多台设备压测一台服务器


```
        // 默认的请求超时时间为3秒
         timeout = 3 * time.Second

	client := &http.Client{
		Transport: tr,
		Timeout:   timeout,
	}
```
