### ISSUE TITLE
支持 http proxy 和 socks5 proxy 吗？

### ISSUE THREAD

**Issue by Su-yj** [link1st/go-stress-testing#126]
能支持设置 proxy 吗？主要是最近写了个代理的程序，想测一下代理的性能

**Comment by link1st** [comment]
可以支持，如果是 HTTP 协议相同的可以直接进行压测

如果是其它协议，可以在 client 处进行改造

https://github.com/link1st/go-stress-testing/blob/master/server/client/http_client.go#L65
