### ISSUE TITLE
执行curl文件不能正确加载host

### ISSUE THREAD

**Issue by xzhacker123** [link1st/go-stress-testing#129]
## 执行命令
./go-stress-testing-mac -p [curl.txt]

## curl文件开头:
`curl --location --request POST 'https://`

## 执行结果:
`请求失败: Post "http://*/*": dial tcp: lookup *: no such host`

后面我检查了一下curl文件，是因为我在curl加了`-k`参数(用来跳过ssl验证)导致的

`curl --location --request POST 'https://xxxx/global/get' -k`

**Comment by link1st** [comment]
我这边没有复现成功，可以将命令拷贝给我看看什么原因导致的

- 复现操作为:
- 执行命令
```
go run main.go -d true -p ./curl/test.curl.txt
```


- **./curl/test.curl.txt** 文件
```
curl --location --request GET 'http://im.91vh.com/user/list?appId=101' -k
```
