### ISSUE TITLE
post类型请求只有一次会成功

### ISSUE THREAD

**Issue by 3638836363** [link1st/go-stress-testing#13]
![image](https://user-images.githubusercontent.com/37776695/74751218-e4364780-52a7-11ea-840b-7ac31c1314c8.png)

**Comment by 3638836363** [comment]
go-stress-testing\server\client\http_client.go line:35
先临时改了这里可以用，有空帮忙看下怎么优化
	req, err := http.NewRequest(method, url, strings.NewReader("id=57"))	 //add
	// req, err := http.NewRequest(method, url, body)

**Comment by link1st** [comment]
谢谢，我刚才试了也发现了这个问题，原因在 `io.Reader` 在 HttpRequest 只能读取一次数据，导致第二次请求就是出现 `http.noBody{}`

问题已经修复

[问题修复](https://github.com/link1st/go-stress-testing/commit/9ecc1f19f67d623cee70f25f4ca96e9d78dd2d31)

**Comment by 3638836363** [comment]
好的，谢谢，我去测试以下

**Comment by 3638836363** [comment]
谢谢
