### ISSUE TITLE
溢出bug

### ISSUE THREAD

**Issue by THMAIL** [link1st/go-stress-testing#139]
go-stress-testing/tree/master/server/statistics/statistics.go文件中148行，
`qps = float64(successNum*1e9*concurrent) / float64(processingTime)`

存在数据溢出，导致qps表现为突降

**Comment by link1st** [comment]
已经修复了

https://github.com/link1st/go-stress-testing/commit/b5069483afcb2cc38504591a5ad9d89a35e86e15
