### ISSUE TITLE
json模板校验需求

### ISSUE THREAD

**Issue by 3638836363** [link1st/go-stress-testing#14]
在实际应用中对于接口请求返回的校验。不同项目可能方式不一样
A: {"code":200,"msg":"Success","data":{}}
B: {"httpCode":200,"status":"Success","info":{}}
... 
诸如此类，我目前想到的方法是直接添加校验模板，通过参数代入。
有没有更好的方案，对Go这块不是很熟悉

**Comment by link1st** [comment]
因为校验不同的项目都是不一样的，这里推荐使用参数的方式传入不同的校验模板

```
Usage of ./go-stress-testing-mac:
  -c uint
        并发数 (default 1)
  -d string
        调试模式 (default "false")
  -n uint
        请求总数 (default 1)
  -p string
        curl文件路径
  -u string
        请求地址
  -v string
        验证方法 http 支持:statusCode、json webSocket支持:json (default "statusCode")
```

- 添加校验验证模板的方式

[http_verify 添加校验验证模板](https://github.com/link1st/go-stress-testing/blob/master/server/verify/http_verify.go)

[注册验证器](https://github.com/link1st/go-stress-testing/blob/master/server/dispose.go)

```
// 注册验证器
func init() {

	// http
	model.RegisterVerifyHttp("statusCode", verify.HttpStatusCode)
	model.RegisterVerifyHttp("json", verify.HttpJson)

	// webSocket
	model.RegisterVerifyWebSocket("json", verify.WebSocketJson)
}
```

**Comment by 3638836363** [comment]
收到，谢谢
