### ISSUE TITLE
mac intel x64

### ISSUE THREAD

**Issue by savico-swee** [link1st/go-stress-testing#140]
sudo: unable to execute ./go-stress-testing-mac: Bad CPU type in executable

**Comment by Lyzin** [comment]
看样子是这个仓库release的mac二进制没有支持64位，我自己重新在intl64的mac打包，就可以运行了

mac64机器打包
`go build -o go-stress-testing-mac-intel64 main.go`

**Comment by savico-swee** [comment]
谢谢～ 我后来用的压缩包安装了一下，发现是OK的

**Comment by link1st** [comment]
新增 mac m1 和 mac intel64 可执行文件

https://github.com/link1st/go-stress-testing/releases/tag/v1.0.8
