### ISSUE TITLE
请求websocket 需要发送message的 怎么使用呢？

### ISSUE THREAD

**Issue by mm8m6m7m** [link1st/go-stress-testing#146]
请求websocket 需要发送message的 怎么使用呢？

**Comment by link1st** [comment]
web 数据不能通过参数的方式进行传递，可以下载源码在以下代码位置进行修改测试

https://github.com/link1st/go-stress-testing/blob/master/server/golink/websocket_link.go#L78

[源码运行教程](https://github.com/link1st/go-stress-testing/tree/master?tab=readme-ov-file#4go-stress-testing-go%E8%AF%AD%E8%A8%80%E5%AE%9E%E7%8E%B0%E7%9A%84%E5%8E%8B%E6%B5%8B%E5%B7%A5%E5%85%B7)
