### ISSUE TITLE
支持禁用/开启 HTTP 重定向

### ISSUE THREAD

**Issue by beihai0xff** [link1st/go-stress-testing#148]
默认情况下，Go HTTP Client 会对 301/302 状态码进行重定向请求，但在某些场景下，需要对中间件服务进行压力测试，而不关心 Real Server 的响应延迟、QPS 等指标，例如短链服务/Gateway 等。
在上述场景下，我们希望能够通过命令行参数，禁用 HTTP Client 的重定向操作，通过自定义 [CheckRedirect](https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/net/http/client.go;l=77) 方法，告知 HTTP Client 不进行重定向。
```
client.CheckRedirect = func(req *http.Request, via []*http.Request) error {
	return http.ErrUseLastResponse
}
```
我在个人分支上已验证上述处理方式有效，并可以提交 PR 将该功能合入到 repo 中。

**Comment by beihai0xff** [comment]
commit 信息 [新增参数 redirect](https://github.com/beihai0xff/go-stress-testing/commit/05785ee398c1f3a8dcd955e572d91cecf7fd6e7b)

**Comment by link1st** [comment]
建议提交 [Pull requests](https://github.com/link1st/go-stress-testing/pulls) ，将 beihai0xff 分支 合并到 master 分支
