### ISSUE TITLE
postman导出的curl不能使用

### ISSUE THREAD

**Issue by zohar-soul** [link1st/go-stress-testing#15]
提示不是正确的http请求

**Comment by link1st** [comment]
如果接口数据不是机密的话，能否发一下导出的postman数据，我这边排查一下原因？

**Comment by zohar-soul** [comment]
@link1st 
```
curl --location --request POST 'api.yuedu.best/yuedu/searchBook' \
--header 'Content-Type: application/json' \
--header 'Content-Type: text/plain' \
--data-raw '{
    "key": "剑来",
    "bookSourceUrl": "https://m.shouda8.com"
}'
```

**Comment by link1st** [comment]
收到，我排查一下原因

**Comment by susengo** [comment]
我也遇到同样的问题，浏览器copy的cURL是可以用的。

**Comment by susengo** [comment]
浏览器拷贝的cURL，无法解析POST请求

**Comment by link1st** [comment]
@zohar-soul  这边已经修复完成了，再试试是否可以了？

下载最新源码编译执行，或者是下载可执行文件
[可执行文件](https://github.com/link1st/go-stress-testing/releases/tag/v1.0.1)

**Comment by link1st** [comment]
> 浏览器拷贝的cURL，无法解析POST请求

下载最新源码编译执行，或者是下载可执行文件
[可执行文件](https://github.com/link1st/go-stress-testing/releases/tag/v1.0.1)

**Comment by zohar-soul** [comment]
@link1st 
我试一下

**Comment by zohar-soul** [comment]
@link1st 
可以了,非常感谢..
一直想找个能直接使用curl的压测工具
