### ISSUE TITLE
import path

### ISSUE THREAD

**Issue by zhaohailin111** [link1st/go-stress-testing#17]
https://github.com/link1st/go-stress-testing/blob/166953ca4f1db6b3565d80c5bd17e1d4f889a097/main.go#L13

这里应该是"github.com/link1st/go-stress-testing/model"吧

**Comment by link1st** [comment]
我的项目目录是在 **src/go-stress-testing** 所以这里不是 `github.com/link1st/go-stress-testing/model`

后续会考虑统一修改为 `github.com/link1st/go-stress-testing/model`

**Comment by zhaohailin111** [comment]
OK
