### ISSUE TITLE
http 短连接

### ISSUE THREAD

**Issue by zhaohailin111** [link1st/go-stress-testing#18]
使用的是http短连接，我实际使用过程中出现了客户端大量time_wait问题。

**Comment by link1st** [comment]
## 7.常见问题
- **Q:** 压测过程中服务器出现大量 **TIME_WAIT**

 A: 参考TCP四次挥手原理，主动关闭连接的一方会出现 **TIME_WAIT** 状态，等待的时长为 2MSL(约1分钟左右)

 原因是：主动断开的一方回复 ACK 消息可能丢失，TCP 是可靠的传输协议，在没有收到 ACK 消息的另一端会重试，重新发送FIN消息，所以主动关闭的一方会等待 2MSL 时间，防止对方重试，这就出现了大量 **TIME_WAIT** 状态（参考: 四次挥手的最后两次）

TCP 握手：
![TCP握手](https://img.mukewang.com/5ec504300001aa7b08301233.png))

**Comment by zhaohailin111** [comment]
![image](https://user-images.githubusercontent.com/34361785/82438053-0455ec80-9acb-11ea-84c1-cfa31faa055a.png)
嗯，实际在运行的时候会遇到这个问题。我看代码中是每个gr都创建一个client的，没有使用连接池

**Comment by zhaohailin111** [comment]
`tr := &http.Transport{
		Proxy: http.ProxyFromEnvironment,
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 90 * time.Second,
		}).DialContext,
		MaxIdleConns:        1000,
		MaxIdleConnsPerHost: 1000,
		IdleConnTimeout:	 90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
		// TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}

	httpClient := &http.Client{
		Transport: tr,
		Timeout:   request.Timeout,
	}`

我用此方法解决了这个问题

**Comment by link1st** [comment]
压测时候用 KeepAlive 复用同一个TCP连接

多个 HTTP 请求用同一个 TCP 连接，这样减少了 TCP 连接的创建也会相应的减少 **TIME_WAIT** 的数量
