### ISSUE TITLE
提示 cannot find package "go-stress-testing/model" in any of

### ISSUE THREAD

**Issue by ydx123mike** [link1st/go-stress-testing#20]
➜  go-stress-testing git:(master) go run main.go -c 1 -n 100 -u https://www.baidu.com/
main.go:13:2: cannot find package "go-stress-testing/model" in any of:
        /usr/local/go/src/go-stress-testing/model (from $GOROOT)
        /Users/mac/go/src/go-stress-testing/model (from $GOPATH)
main.go:14:2: cannot find package "go-stress-testing/server" in any of:
        /usr/local/go/src/go-stress-testing/server (from $GOROOT)
        /Users/mac/go/src/go-stress-testing/server (from $GOPATH)
➜  go-stress-testing git:(master)

**Comment by link1st** [comment]
请将项目 clone 到 **$GOPATH** 目录下面 `/Users/mac/go/src/`
