### ISSUE TITLE
 如何避免大量TIME_WAIT？

### ISSUE THREAD

**Issue by sanxun0325** [link1st/go-stress-testing#21]
你好，通过go夜读了解到这个项目，想问一下在压测过程中 如何尽量避免大量出现TIME_WAIT？
通过增大超时时间的设置么。

**Comment by link1st** [comment]
[压测过程中会出现大量 TIME_WAIT](https://github.com/link1st/go-stress-testing#7%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

TIME_WAIT 其实是正常现象，再压测http接口都是都是短连接，每次建立连接的时候都会出现 TIME_WAIT，除非压测的时候建立长链接，只压测数据

[保持连接KeepAlive](https://github.com/link1st/go-stress-testing/issues/18)

**Comment by sanxun0325** [comment]
@link1st 谢谢。还有一个这样的问题。
connect: cannot assign requested address

![image](https://user-images.githubusercontent.com/28588342/85102838-0c26bf00-b238-11ea-88ae-a5cbd086b5f2.png)

**Comment by sanxun0325** [comment]
@link1st 
如下图，第一秒的时候并发数是4，是代表在第一秒中的时候 只有四个并发么。如果是这样的话，那QPS却是4W多。不知道这些数据怎么算出来的。

![image](https://user-images.githubusercontent.com/28588342/85190187-63846800-b2e8-11ea-8e26-1f771c9dfe5f.png)

**Comment by link1st** [comment]
问题一:
connect: cannot assign requested address
无法分配请求地址，因为在TCP 连接的时候client需要占用一个端口，但是本地的端口是有限的，所以会出现无法分配端口的现象

解决:
设置更多的可用端口、修改地址快速回收


问题二:
QPS: 指的是一秒钟请求接口次数，这里平均耗时为 0.02 毫秒
QPS=1s*1000/0.02 等于50000，显示 0.02 毫秒因为小数舍去了，所以是40213.41
