### ISSUE TITLE
和wrk对比，压测结果差距很大

### ISSUE THREAD

**Issue by mrzxy** [link1st/go-stress-testing#24]
1.go-stress-testing
![image](https://user-images.githubusercontent.com/11501927/86227010-11ccbf00-bbbf-11ea-88f0-67920145bf45.png)

2.wrk
![image](https://user-images.githubusercontent.com/11501927/86227076-2315cb80-bbbf-11ea-928d-67e5984e48f7.png)

**Comment by link1st** [comment]
go-stress-testing 在计算请求的HTTP接口的响应时长，除了计算网络请求的时间也将数据处理的时间也计算在内了

后续打算将这部分时间移除，以后统计时长只计算网络请求的时间

**Comment by mrzxy** [comment]
感谢回复

**Comment by yiippee** [comment]
![image](https://user-images.githubusercontent.com/37373803/97437728-d8cf0c00-195e-11eb-8a20-88f971fa48f7.png)
你好，server.go 用的是你给的例子，我这边测试的qps相差有10多倍啊，请问是我哪里操作不对吗？谢谢。
