### ISSUE TITLE
webSocket发送和读取数据

### ISSUE THREAD

**Issue by kenyyyyyy** [link1st/go-stress-testing#25]
![image](https://user-images.githubusercontent.com/43124889/86574620-b2005a80-bfa8-11ea-8056-af5f0e7c2d8a.png)
求问，这里的数据发送和数据读取为什么要怎么写？
我认为webSocket数据发送和数据读取是平行的。数据不能发送不代表不能接收数据吧？

**Comment by link1st** [comment]
问题一:
这里压测的 webSocket 服务端是我的另一个项目，协议定义如下:

[webSocket server 接口文档](https://github.com/link1st/gowebsocket#33-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF)

问题二:
因为这边是模拟 客户端发送数据请求，如果发送数据都失败了，可以接受到也就没有意义了
