### ISSUE TITLE
平均耗时普遍比最短耗时还要小

### ISSUE THREAD

**Issue by jdy879526487** [link1st/go-stress-testing#26]
平均耗时普遍比最短耗时还要小,是我对这个平均耗时理解有偏差吗, 它的具体意义 到底是什么呢?

**Comment by jdy879526487** [comment]
可以给一下计算公式吗，代码中我看到有 除一个协程数, 我把协程数乘回去刚好符合自己的预测

**Comment by link1st** [comment]
本项目是并发压测的
QPS = 服务器每秒钟处理请求数量 (req/sec 请求数/秒) 

定义：单个协程耗时T, 所有协程压测总时间 sumT,协程数 n

如果:只有一个协程，假设接口耗时为 2毫秒，每个协程请求了10次接口，每个协程耗总耗时2*10=20毫秒,sumT=20
`QPS = 10/20*1000=500`

如果:只有十个协程，假设接口耗时为 2毫秒,每个协程请求了10次接口，每个协程耗总耗时2*10=20毫秒,sumT=20*10=200
`QPS = 100/(200/10)*1000=5000`  

上诉两个示例现实中总耗时都是20毫秒，示例二 请求了100次接口，QPS应该为 示例一 的10倍，所以示例二的实际总**QPS为5000**

除以协程数的意义是，sumT是所有协程耗时总和

**Comment by jdy879526487** [comment]
好的，明白了，谢啦

**Comment by yyltesting** [comment]
> 本项目是并发压测的 QPS = 服务器每秒钟处理请求数量 (req/sec 请求数/秒)
> 
> 定义：单个协程耗时T, 所有协程压测总时间 sumT,协程数 n
> 
> 如果:只有一个协程，假设接口耗时为 2毫秒，每个协程请求了10次接口，每个协程耗总耗时2*10=20毫秒,sumT=20 `QPS = 10/20*1000=500`
> 
> 如果:只有十个协程，假设接口耗时为 2毫秒,每个协程请求了10次接口，每个协程耗总耗时2*10=20毫秒,sumT=`20*10`=200 `QPS = 100/(200/10)*1000=5000`
> 
> 上诉两个示例现实中总耗时都是20毫秒，示例二 请求了100次接口，QPS应该为 示例一 的10倍，所以示例二的实际总**QPS为5000**
> 
> 除以协程数的意义是，sumT是所有协程耗时总和

我看代码除以的协程数是固定的，但是实际可能处理的协程数当前的协程数是动态的吧 总觉得QPS没怎么算对

**Comment by yyltesting** [comment]
> QPS = 100/(200/10)*1000=5000

你的并发数每次都是固定的并发数去计算的 应该是动态实际请求的并发协程数去计算吧

**Comment by link1st** [comment]
> > QPS = 100/(200/10)*1000=5000
> 
> 你的并发数每次都是固定的并发数去计算的 应该是动态实际请求的并发协程数去计算吧 用chanIDLen才对吧？

@yyltesting 目前使用的是固定的并发数计算的

- 如果是使用动态协程数 chanIDLen 计算QPS，会导致QPS比较高
> 程序是先启动协程，每个协程开始并发请求服务端，类似于"跑马"效果，如果使用 动态协程数，最早的 QPS 是就会使用跑马最快的一个或者是几个计算QPS
> 会导致平均耗时很低(跑马中最快的)，QPS 会虚高

- QPS  应该是压测一段时间，并发数一定 QPS 稳定在一个数值的访问才是在该并发下服务端的实际QPS
- 所以，这里使用的是固定并发数计算的更合理

**Comment by yyltesting** [comment]
> 本项目是并发压测的 QPS = 服务器每秒钟处理请求数量 (req/sec 请求数/秒)
> 
> 定义：单个协程耗时T, 所有协程压测总时间 sumT,协程数 n
> 
> 如果:只有一个协程，假设接口耗时为 2毫秒，每个协程请求了10次接口，每个协程耗总耗时2*10=20毫秒,sumT=20 `QPS = 10/20*1000=500`
> 
> 如果:只有十个协程，假设接口耗时为 2毫秒,每个协程请求了10次接口，每个协程耗总耗时2*10=20毫秒,sumT=`20*10`=200 `QPS = 100/(200/10)*1000=5000`
> 
> 上诉两个示例现实中总耗时都是20毫秒，示例二 请求了100次接口，QPS应该为 示例一 的10倍，所以示例二的实际总**QPS为5000**
> 
> 除以协程数的意义是，sumT是所有协程耗时总和

你这里的耗时是把每个并发协程请求的耗时相加/总协程。 如果我只用了十个协程，每个只请求一次，这里算的耗时变成了平均耗时时长，而且十个协程是没有先后的，如果是按时间相加来计算肯定不对吧。服务器是同时处理的，比如十个请求总共耗时1秒（有些是0.5秒就处理了，有些是0.9秒，有些是1秒），对于服务器是一秒处理了十个请求那么QPS是10，但是按现在这种计算每个协程的耗时相加除以协程数，QPS肯定大于10
