### ISSUE TITLE
可以实现jmeter那种模拟用户的登录,浏览,退出这种步骤行的压力测试么

### ISSUE THREAD

**Issue by oldthreefeng** [link1st/go-stress-testing#28]
如题~

**Comment by link1st** [comment]
是需要一次性压测多个接口吗？

**Comment by oldthreefeng** [comment]
对的。

**Comment by link1st** [comment]
终端只支持单个接口压测，如果是分布压测需要 写一部分go代码

[填写需要的压测的接口](https://github.com/link1st/go-stress-testing/blob/master/server/golink/http_link.go#L32)

**Comment by oldthreefeng** [comment]
> 
> 
> 终端只支持单个接口压测，如果是分布压测需要 写一部分go代码
> 
> [填写需要的压测的接口](https://github.com/link1st/go-stress-testing/blob/master/server/golink/http_link.go#L32)


能稍微写点么.   借鉴一下. 分布压测的实现..

**Comment by link1st** [comment]
已经添加 
[分步压测示例代码](https://github.com/link1st/go-stress-testing/blob/master/server/golink/http_link_many.go) 
[加权压测示例代码](https://github.com/link1st/go-stress-testing/blob/master/server/golink/http_link_weigh.go)
