### ISSUE TITLE
windows 下链接断开会报错 An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ss22219** [link1st/go-stress-testing#33]
我执行如下命令：`.\go-stress-testing-win.exe -c 16 -n 1000 -u  http://localhost/foo`
其中会有一些错误提示影响查看统计数据：

请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64169->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64174->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64173->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
 128s│     16│  15758│     67│  146.94│21119.76│    2.99│    6.81│200:15758;509:67
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64186->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64202->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64203->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
ly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64210->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64213->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64214->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64219->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64226->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64220->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64227->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64228->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
请求失败: Get "http://localhost/foo": read tcp 127.0.0.1:64233->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by link1st** [comment]
你好，这边看上去好像是服务端 (80端口)  强制关闭了连接
