### ISSUE TITLE
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address

### ISSUE THREAD

**Issue by tanjunchen** [link1st/go-stress-testing#35]
在同一台机器上测试：
先起服务 
go  run tests/servers.go

后面测试：

[root@test-10 go-stress-testing]# go run main.go -c 100 -n 10000 -u http://127.0.0.1:8088/

 开始启动  并发数:100 请求数:10000 请求参数: 
request:
 form:http 
 url:http://127.0.0.1:8088/ 
 method:GET 
 headers:map[] 
 data: 
 verify:statusCode 
 timeout:30s 
 debug:false 

─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────
 耗时│ 并发数│ 成功数│ 失败数│   qps  │最长耗时│最短耗时│平均耗时│ 错误码
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────
   1s│    100│   4846│      0│ 6372.45│   40.35│    1.25│   15.69│200:4846
   2s│    100│  10022│      0│ 6510.04│   40.35│    0.98│   15.36│200:10022
   3s│    100│  14961│      0│ 6448.37│   40.35│    0.98│   15.51│200:14961
   4s│    100│  19938│      0│ 6451.98│   40.35│    0.98│   15.50│200:19938
   5s│    100│  24869│      0│ 6443.08│   40.35│    0.98│   15.52│200:24869
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address
请求失败: Get http://127.0.0.1:8088/: dial tcp 127.0.0.1:8088: connect: cannot assign requested address

**Comment by link1st** [comment]
connect: cannot assign requested address 

client端频繁建立连接，而端口释放较慢，导致建立新连接时无可用端口。
报错的原因是本地的socket 连接用光，可以提高ulimit 数或者是tcp端口快速回收

```
ulimit -n 10240
```

或者

```
vim /etc/sysctl.conf
 
 # 加入
net.ipv4.tcp_tw_reuse = 1 
net.ipv4.tcp_tw_recycle = 1
```

**Comment by tanjunchen** [comment]
好的 有空我试试 谢谢

**Comment by yiippee** [comment]
─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────
 耗时│ 并发数│ 成功数│ 失败数│   qps  │最长耗时│最短耗时│平均耗时│ 错误码
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────
   1s│    100│   4793│      0│ 6672.50│   31.62│    0.90│   14.99│200:4793
   2s│    100│   9750│      0│ 6725.74│   31.62│    0.59│   14.87│200:9750
   3s│    100│  14737│      0│ 6756.47│   31.91│    0.43│   14.80│200:14737
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused
请求失败: Get "http://127.0.0.1:8088/": dial tcp 127.0.0.1:8088: connect: connection refused

你好，请问我上面这种错误是什么原因呢？谢谢。通过浏览器访问127.0.0.1:8088是可以的。

**Comment by link1st** [comment]
这个是压测强度过大，服务端拒绝连接了
