### ISSUE TITLE
某些情况导致程序崩溃

### ISSUE THREAD

**Issue by sishui** [link1st/go-stress-testing#40]
https://github.com/link1st/go-stress-testing/blob/2e573d19e97b24cd239817a30167bf3ee58e0777/server/statistics/statistics.go#L191

requestTimeFloat 小于1 的时候，int64(requestTimeFloat) 就会等于0

**Comment by link1st** [comment]
感谢提出问题，已经更新

[fix bug](https://github.com/link1st/go-stress-testing/commit/ee43255ba5689a4eaac5faad97f99f856d45c9a1)

**Comment by sishui** [comment]
并没修复哈，我提了个pr，你看看对不对

**Comment by link1st** [comment]
- [pr](https://github.com/link1st/go-stress-testing/pull/42/files) 这么处理避免了 requestTimeFloat float 小于1 强转 int 会变0的情况
- 但是 requestTimeFloat 可能为 0 

```
int64(float64(receivedBytes)/requestTimeFloat)
```

**Comment by sishui** [comment]
嗯 是的，requestTimeFloat还是有为0的概率，我想这里可能只能做个容错了
