### ISSUE TITLE
平均耗时好像不对？

### ISSUE THREAD

**Issue by idonkeyliu** [link1st/go-stress-testing#43]
─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────
 耗时│ 并发数│ 成功数│ 失败数│   qps  │最长耗时│最短耗时│平均耗时│ 错误码
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────
   1s│     10│    162│      0│  166.76│   83.38│   53.16│    6.00│200:162
   2s│     10│    324│      0│  164.51│  102.15│   52.10│    6.08│200:324
   3s│     10│    489│      0│  165.25│  102.15│   52.10│    6.05│200:489
   4s│     10│    662│      0│  166.60│  102.15│   51.64│    6.00│200:662
   5s│     10│    822│      0│  165.70│  107.08│   51.64│    6.04│200:822
   6s│     10│    991│      0│  166.29│  107.08│   51.18│    6.01│200:991
   6s│     10│   1000│      0│  166.32│  107.08│   51.18│    6.01│200:1000

**Comment by link1st** [comment]
之前平均耗时采用的是服务器的平均耗时，已经更新为了客户端的平均耗时，可以下载最新编译包


[最新编译包](https://github.com/link1st/go-stress-testing/releases/tag/v0.1.4)

**Comment by idonkeyliu** [comment]
好的，谢谢啦~

**Comment by idonkeyliu** [comment]
panic: runtime error: integer divide by zero

**Comment by link1st** [comment]
麻烦重新下载一下最新安装包 [最新安装包](https://github.com/link1st/go-stress-testing/releases/tag/v0.1.4)，或者是git clone  master 分支进行编译

**panic: runtime error: integer divide by zero** 是由于我本地不是最新代码，已经重新编译了

**Comment by idonkeyliu** [comment]
为什么用debug模式的时候，有些返回body有值，有些没有呢

**Comment by idonkeyliu** [comment]
这个压测能加上断言吗

**Comment by link1st** [comment]
用debug 模式，这个有实例数据吗？

**Comment by link1st** [comment]
如果需要用数据校验，可以使用`-v` 参数，或者自己扩展校验的方式

```
  -v string
      验证方法 http 支持:statusCode、json webSocket支持:json
```
