### ISSUE TITLE
connectionMode = 2

### ISSUE THREAD

**Issue by wzhsh90** [link1st/go-stress-testing#46]
修改connectionMode = 2 后

connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or es
tablished connection failed because connected host has failed to respond.
exit status 2

我要测试5000个单机效果
创建到1560个websocket 并发测试，就报上面错误了

**Comment by wzhsh90** [comment]
我win10 16g内存，

![Uploading image.png…]()

只能跑1012个？

**Comment by wzhsh90** [comment]
换成linux 8核16g 最多也只跑到1005
![Uploading image.png…]()

**Comment by wzhsh90** [comment]
./main  -c 2000 -n 10  -u

这个是什么原因？
goroutine 3685 [chan receive]:
go-stress-testing/server/golink.WebSocket(0x71b, 0xc000058360, 0xa, 0xc0000143d4, 0xc000010310, 0xc0019944b0)
	E:/goworkspace/go-stress-testing/server/golink/websocket_link.go:55 +0xb5
created by go-stress-testing/server.Dispose
	E:/goworkspace/go-stress-testing/server/dispose.go:74 +0x448

**Comment by link1st** [comment]
> 修改connectionMode = 2 后
> 
> connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or es
> tablished connection failed because connected host has failed to respond.
> exit status 2
> 
> 我要测试5000个单机效果
> 创建到1560个websocket 并发测试，就报上面错误了

看样子好像是 server 连接拒绝了？

**Comment by link1st** [comment]
> 换成linux 8核16g 最多也只跑到1005

图片我这边都加载不出来

**Comment by link1st** [comment]
> ./main -c 2000 -n 10 -u
> 
> 这个是什么原因？
> goroutine 3685 [chan receive]:
> go-stress-testing/server/golink.WebSocket(0x71b, 0xc000058360, 0xa, 0xc0000143d4, 0xc000010310, 0xc0019944b0)
> E:/goworkspace/go-stress-testing/server/golink/websocket_link.go:55 +0xb5
> created by go-stress-testing/server.Dispose
> E:/goworkspace/go-stress-testing/server/dispose.go:74 +0x448

是否可以详细描述一下是如何使用的呢？
websocket_link.go:55 是用到了 time 的定时器

```
	t := time.NewTimer(firstTime)
	for {
		select {
		case <-t.C:
			t.Reset(intervalTime)

			// 请求
			webSocketRequest(chanId, ch, i, request, ws)

			// 结束条件
			i = i + 1
			if i >= totalNumber {
				goto end
			}
		}
	}
```
