### ISSUE TITLE
failed to exec echo 'fatal error: concurrent map iteration and map write. when 

### ISSUE THREAD

**Issue by zhou1992513** [link1st/go-stress-testing#47]
![image](https://user-images.githubusercontent.com/30553659/103069711-e28d8c80-45fa-11eb-89c7-99647db2e61f.png)

**Comment by link1st** [comment]
https://github.com/link1st/go-stress-testing/blob/46ccbb47e06eacee21551e23f1e5ba2c721d949b/server/statistics/statistics.go#L208

**statistics.go** 这个文件没有 288 行，你用的是哪个版本的？
