### ISSUE TITLE
请教rpc压测如何使用

### ISSUE THREAD

**Issue by scientiacoder** [link1st/go-stress-testing#49]
文档有写可以压测http、webSocket请求、**私有rpc调用**, 可是并未找到具体是如何压测rpc的 请指教 谢谢～

**Comment by link1st** [comment]
这里添加了grpc 接口压测的示例用法，可以参考这个编写你需要的私有协议压测

[grpc 接口压测示例文档](https://github.com/link1st/go-stress-testing#45-grpc%E5%8E%8B%E6%B5%8B)

[grpc 接口压测示例代码 commit](https://github.com/link1st/go-stress-testing/commit/2b4b14aaf026d08276531cf76f42de90efd3bc61)

**Comment by scientiacoder** [comment]
感谢大佬～
