### ISSUE TITLE
how to test tcp server

### ISSUE THREAD

**Issue by 15663671003** [link1st/go-stress-testing#50]

**Comment by link1st** [comment]
- Here is an example usage of grpc interface pressure test, you can refer to this to write the pressure test of the private protocol you need

[grpc interface stress test sample document](https://github.com/link1st/go-stress-testing#45-grpc%E5%8E%8B%E6%B5%8B)

[grpc interface pressure test sample code commit](https://github.com/link1st/go-stress-testing/commit/2b4b14aaf026d08276531cf76f42de90efd3bc61)
