### ISSUE TITLE
statistics.ReceivingResults 单个goroutine是否会影响性能

### ISSUE THREAD

**Issue by PennaLai** [link1st/go-stress-testing#51]
发现在dispose里只开了一个goroutine来收集数据，虽然有channel有1000的buffer，但是应该很快会被占满而使得发送请求阻塞吧

**Comment by link1st** [comment]
这里不会影响性能，压测的大部分消耗都是花在网络请求上，压测的结果通过 channel 传递到 `statistics.ReceivingResults` 处理，这里只是经过简单的数值计算，没有复杂的操作，消耗很少的CPU资源就能完成处理，只开单个 goroutine 完全是够用
