### ISSUE TITLE
当 PUT 方法带 body 时会被当作 POST 提交

### ISSUE THREAD

**Issue by jetking** [link1st/go-stress-testing#55]
我有个接口是使用 PUT 方法进行数据更新，我的 curl 文件大概是这样的：

```
curl -X PUT  http://domain.com/path \
    -H 'content-type: application/json' \
    -H 'Authorization: Bearer ...' \
    -H 'Accept: application/json' \
    -H 'X-Language: zh_cn' \
    -d '{"parts":1}'
```

但会被当作 POST 执行，看了下源码，在  [curl_model.go](https://github.com/link1st/go-stress-testing/blob/4b4ad0a812981fdda75ded8d22a6b1a175b11451/model/curl_model.go#L189) 这个地方直接返回了 POST。

**Comment by link1st** [comment]
https://github.com/link1st/go-stress-testing/blob/e4d4845b5268b93057528b08dcd146bd2c801011/model/curl_model.go#L192

已经修复，之前优先判断是否是POST方法
