### ISSUE TITLE
如果1000个协程每个request的参数不一样（head或者body），Dispose能否做下支持传[]request处理？

### ISSUE THREAD

**Issue by stelth2016** [link1st/go-stress-testing#57]

**Comment by link1st** [comment]
每个接口请求不同，这个就涉及比较多的问题
1、每个协程请求的数据不同
2、每个协程顺序请求接口

由于这个需求不同，就没有实现通用的方法

可以参考这个，编写简单的代码就可以实现
https://github.com/link1st/go-stress-testing/issues/28
