### ISSUE TITLE
是否有计划支持随机参数去压测

### ISSUE THREAD

**Issue by xiao6233305** [link1st/go-stress-testing#60]
从实际工作中，参数都不是固定的，请问是否有考虑支持，我昨天拿着你的代码，简单改了一下支持了随机参数去压测，但是只实现了http的方式的。而且跟现在功能很不兼容，暂时也不好提一个mr过来

**Comment by link1st** [comment]
没有规划支持这个特性，目前没有一个好的方式去实现这个

**Comment by xiao6233305** [comment]
但是最近用这个压测也还好，能满足我自己的需求

**Comment by link1st** [comment]
文件的方式我也考虑过，感觉不是很通用 就没有去实现这种方式

**Comment by yuefei7746** [comment]
> 我现在用的方式是把请求参数都放入一个文件。然后去读取文件。构造成一个slice。然后每次请求随机一个去请求。可能重复。不是很好

这个方式算是比较常规的方式，建议可以支持一下

**Comment by xiao6233305** [comment]
> > 我现在用的方式是把请求参数都放入一个文件。然后去读取文件。构造成一个slice。然后每次请求随机一个去请求。可能重复。不是很好
> 
> 这个方式算是比较常规的方式，建议可以支持一下

我实现了，但是只支持http接口压测，改进了一下，使用CAS操作来实现不重复请求，有空可以一起交流一下。https://github.com/xiao6233305/go-stress-testing
