### ISSUE TITLE
README.md 6.2 内核优化

### ISSUE THREAD

**Issue by Mericusta** [link1st/go-stress-testing#61]
添加以下参数
root soft nofile 1040000 <- repeat 1
root hard nofile 1040000

root soft nofile 1040000 <- repeat 1
root hard nproc 1040000

root soft core unlimited
root hard core unlimited

* soft nofile 1040000 <- repeat 2
* hard nofile 1040000

* soft nofile 1040000 <- repeat 2
* hard nproc 1040000

* soft core unlimited
* hard core unlimited

---

两处重复是否正确？

是否应该修改为

```
root soft nproc 1040000
root hard nproc 1040000

* soft nproc 1040000
* hard nproc 1040000
```

**Comment by link1st** [comment]
感谢指出问题，已经更新为:
> soft nproc ：单个用户可用的最大进程数量(超过会警告);
> hard nproc：单个用户可用的最大进程数量(超过会报错);
> soft nofile ：可打开的文件描述符的最大数(超过会警告);
> hard nofile ：可打开的文件描述符的最大数(超过会报错);
```
root soft nofile 1040000
root hard nofile 1040000
root soft nproc 1040000
root hard nproc 1040000

* soft nofile 1040000
* hard nofile 1040000
* soft nproc 1040000
* hard nproc 1040000

root soft core unlimited
root hard core unlimited

* soft core unlimited
* hard core unlimited
```
