### ISSUE TITLE
怎么验证响应的json结果？

### ISSUE THREAD

**Issue by copysunday** [link1st/go-stress-testing#62]
发现代码里写死了特定的验证逻辑，验证不了业务定义的code

**Comment by link1st** [comment]
https://github.com/link1st/go-stress-testing/blob/master/server/verify/http_verify.go#L62

参考这个，添加参数 ` -v json` 即可调用这个方法验证，判断业务放回code 是否等于200

**Comment by copysunday** [comment]
> https://github.com/link1st/go-stress-testing/blob/master/server/verify/http_verify.go#L62
> 
> 参考这个，添加参数 ` -v json` 即可调用这个方法验证，判断业务放回code 是否等于200

但是我们的响应code=0才是成功，这块有办法支持吗

**Comment by link1st** [comment]
可以将本项目源码下载下来，然后修改校验函数

https://github.com/link1st/go-stress-testing/blob/master/server/verify/http_verify.go#L81
```
				// body 中code返回0为返回数据成功
				if responseJSON.Code == 0 {
					isSucceed = true
				}
```
- 项目重新编译，就可以得到可执行文件了

```
go build
```


附录:
[go 安装教程](https://golang.org/doc/install)

**Comment by copysunday** [comment]
> 可以将本项目源码下载下来，然后修改校验函数
> 
> https://github.com/link1st/go-stress-testing/blob/master/server/verify/http_verify.go#L81
> 
> ```
> 				// body 中code返回0为返回数据成功
> 				if responseJSON.Code == 0 {
> 					isSucceed = true
> 				}
> ```
> 
> * 项目重新编译，就可以得到可执行文件了
> 
> ```
> go build
> ```
> 
> 附录:
> [go 安装教程](https://golang.org/doc/install)

thx
