### ISSUE TITLE
可以考虑 结果stat 显示TP相关信息

### ISSUE THREAD

**Issue by halleyshx** [link1st/go-stress-testing#65]
比如TP50、TP90、TP99、TP999信息

**Comment by link1st** [comment]
这个功能不是特别常用，属于辅助信息 目前没有计划添加

如有需要可以自行修改源码添加:
https://github.com/link1st/go-stress-testing/blob/71100460713276af9b6884519ba0715b84704a96/server/statistics/statistics.go#L155
