### ISSUE TITLE
不能直接兼容postman-curl数据格式吗？

### ISSUE THREAD

**Issue by baiyishaoxia** [link1st/go-stress-testing#69]
经过测试，其他方面都好用，post-data参数只接收了第一行？
但是 herader参数都是一行一行接收了的。。
如下图所示：
![image](https://user-images.githubusercontent.com/34636159/126860423-69cc0499-cda0-45c7-b539-b0d7d38a5259.png)

![image](https://user-images.githubusercontent.com/34636159/126860573-4f25c89b-09b2-4c8e-a8c2-63aff242ace1.png)

**Comment by link1st** [comment]
是的，目前post data 只能单行提交，postman 导出的 curl 不同版本是不一样的，之前兼容过几次
