### ISSUE TITLE
并发测试参数丢失

### ISSUE THREAD

**Issue by applytogetintoyourlife** [link1st/go-stress-testing#71]
curl  test.txt:
![image](https://user-images.githubusercontent.com/42194819/128314513-0c838a61-9113-4e50-bb98-4e3b63baa4b0.png)

接收的接口:

![image](https://user-images.githubusercontent.com/42194819/128314667-8a6e010e-5330-47f3-8401-e863099ddee7.png)

mysql数据表

![image](https://user-images.githubusercontent.com/42194819/128314715-d0d3db9d-c8bb-4d58-9c12-3242efafd258.png)

执行压测请求命令:
`go run main.go -c 5 -n 5 -p curl/test.txt
`
输出结果:
`D:\go\stress-testing>go run main.go -c 5 -n 5 -p curl/test.txt

 开始启动  并发数:5 请求数:5 请求参数:

![image](https://user-images.githubusercontent.com/42194819/128314895-4d39b42a-6ab8-4adb-adad-f530f3197314.png)
![image](https://user-images.githubusercontent.com/42194819/128314922-e7e081be-3dd8-43bc-b0c8-cef33129d70c.png)

**实际发送了25个请求,但是其中6个请求出现了参数丢失的情况**

`D:\go\model-test>go run main.go

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17  -

2021/08/05 15:58:17  -

2021/08/05 15:58:17  -

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17  -

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17  -

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17  -

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18

2021/08/05 15:58:17 张三 - 18
`

插入的数据库结果:
![image](https://user-images.githubusercontent.com/42194819/128314180-14e8aba6-e490-4be2-9dee-af15ad58ac02.png)

**Comment by link1st** [comment]
发送 HTTP 协议数据结构如下:
```
POST / HTTP/1.1
User-Agent: PostmanRuntime/7.28.2
Accept: */*
Postman-Token: e7e226ee-302b-4cd0-a85b-afcc6e39fc4b
Host: 127.0.0.1:8088
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------560261116256263716880757
Content-Length: 165
 
----------------------------560261116256263716880757
Content-Disposition: form-data; name="name"
张三
----------------------------560261116256263716880757--
 
HTTP/1.1 200 OK
Server: golang
Date: Thu, 05 Aug 2021 09:05:49 GMT
Content-Length: 27
Content-Type: text/plain; charset=utf-8
 
Hello, go-stress-testing!
```

HTTP POST multipart/form-data 协议格式，会有一个随机数 `560261116256263716880757`，相同的随机数会在go server 认为是同一个请求，在使用 `io.Read` 只能读取一次，后者读取到的就为空，所有会出现数据丢失的现象

建议使用:
HTTP POST x-www-form-urlencoded 或者 GET 请求

**Comment by whistling** [comment]
json 并发请求也是 参数丢失 @link1st
