### ISSUE TITLE
Invalid upstream response (403)

### ISSUE THREAD

**Issue by panol** [link1st/go-stress-testing#74]
访问首页文档如下的超链接,响应:
Invalid upstream response (403)
I: chrome 浏览器生成 curl文件，打开开发者模式(快捷键F12)，如图所示，生成 curl 在终端执行命令 chrome cURL

II: postman 生成 curl 命令 postman cURL

**Comment by link1st** [comment]
之前使用的图片源失效了，现在已经更新了
