### ISSUE TITLE
出现并发问题

### ISSUE THREAD

**Issue by crimson-gao** [link1st/go-stress-testing#78]
`go run -race main.go -c 10 -n 10 -u https://www.baidu.com/` 测试通不过，看了下代码，应该是采集数据那里没做并发处理。
多个线程直接向同一个变量，比如 `	statistics.RequestTimeList = append(statistics.RequestTimeList, requestTime`  
解决方式也很简单，不再直接修改共享变量，而是通过一个共享的 channel 传输数据。 client 往里面写，统计数据的读就好了。

统计数据的的那个线程完全可以 
```golang
ticker := time.NewTicker(time.Second)
for{
  select{
  case res:= <- resultChan:  doSomething() // 统计数据
  case <- ticker.C:  printTable()  // 计算数据并打印出结果
  case <- stopChan : quit()  // 直接退出, 或者 goto out 打印总的统计结果也好
  }
}
```
一个线程就够了

**Comment by link1st** [comment]
感谢支出问题，已经修复了，之前没有注意并发下的竞争

**Comment by crimson-gao** [comment]
👍赞
