### ISSUE TITLE
请问下断言和参数化怎么做？还有组合场景

### ISSUE THREAD

**Issue by jackiezero** [link1st/go-stress-testing#79]
1. 类似于第二个接口依托于第一个接口的返回结果
2. 接口请求参数每次调用的时候都取不同的值

**Comment by link1st** [comment]
可以参考这个，分步压测，需要自己写 go 代码实现

[分步压测示例](https://github.com/link1st/go-stress-testing/commit/760552c7c1e951134cf65b0d6d78274365edbfa1)
