### ISSUE TITLE
返回值result应该判空吧？

### ISSUE THREAD

**Issue by csh0101** [link1st/go-stress-testing#80]
`
sort.Sort(all)

	fmt.Printf("\n\n")
	fmt.Println("*************************  结果 stat  ****************************")
	fmt.Println("处理协程数量:", concurrent)
	// fmt.Println("处理协程数量:", concurrent, "程序处理总时长:", fmt.Sprintf("%.3f", float64(processingTime/concurrent)/1e9), "秒")
	fmt.Println("请求总数（并发数*请求数 -c * -n）:", successNum+failureNum, "总请求时间:",
		fmt.Sprintf("%.3f", float64(requestTime)/1e9),
		"秒", "successNum:", successNum, "failureNum:", failureNum)

	fmt.Println("tp90:", fmt.Sprintf("%.3f", float64(all[int(float64(len(all))*0.90)]/1e6)))
	fmt.Println("tp95:", fmt.Sprintf("%.3f", float64(all[int(float64(len(all))*0.95)]/1e6)))
	fmt.Println("tp99:", fmt.Sprintf("%.3f", float64(all[int(float64(len(all))*0.99)]/1e6)))
	fmt.Println("*************************  结果 end   ****************************")
	fmt.Printf("\n\n")
`
all没有判空直接取all直接panic了

**Comment by link1st** [comment]
已经更新


https://github.com/link1st/go-stress-testing/commit/196bf8b282980302285de7eaec5aeae0a5c764ff
