### ISSUE TITLE
运行卡住不动

### ISSUE THREAD

**Issue by pea-cake** [link1st/go-stress-testing#83]
![image](https://user-images.githubusercontent.com/58544092/148487488-091ee301-c527-43ec-b982-01bb0306b5d1.png)

**Comment by pea-cake** [comment]
用了v_p_n也不行🥲🥲🥲

**Comment by link1st** [comment]
这个看着像是 go 下载依赖包没有成功，看着像网的原因
如果研究源码可以使用 [go 使用中国源](https://learnku.com/go/wikis/38122) 可以提升下载速度

**Comment by pea-cake** [comment]
> 

好的，谢谢🧍‍♂️
