### ISSUE TITLE
是否可以测定服务端交易到达率？

### ISSUE THREAD

**Issue by TianshuDing** [link1st/go-stress-testing#86]
比如50个客户端，每个客户端一秒发送10次请求，服务端是否是一秒到达500个请求？
本项目好像没有设置发送时间间隔，希望能够看到服务端TPS随请求速率的变化，以此判定服务端的TPS上限。
假设服务端TPS上限1000，交易到达速率小于1000就测不出TPS上限，高于1000则会看到TPS不在显著增长，而请求延迟在显著增加

**Comment by link1st** [comment]
- 本项目其实是客户端，50个客户端一秒发送10次请求，可能服务端接收到了 490个请求，客户端最终收到了 480个请求，
- 在请求和返回的过程中涉及网络问题，可能在发送的时候丢失了10个，返回的时候又丢失了
- 本项目可以记录到的到达率为 480/500，(通过错误码一栏查看)
> 比如50个客户端，每个客户端一秒发送10次请求，服务端是否是一秒到达500个请求？
- 本项目支持调整 并发数，和每个并发发送请求个数，通过这个参数调整 查看服务端 TPS 是否会增加来判断上限
> 判定服务端的TPS上限。
