### ISSUE TITLE
可否支持将测试报告导出为 markdown 文件

### ISSUE THREAD

**Issue by frei-x** [link1st/go-stress-testing#89]

**Comment by link1st** [comment]
需要的是什么样式的 markdown 文件呢？

目前是以纯文本的方式输出到终端的

**Comment by frei-x** [comment]
> 需要的是什么样式的 markdown 文件呢？
> 
> 目前是以纯文本的方式输出到终端的

markdown 表格。  因为 txt 不同屏幕显示差别大， 表格表头对不齐， 不方便看。

感谢！

**Comment by link1st** [comment]
可以提 MR 的方式，如果测试没有问题 可以合并到 master

**Comment by link1st** [comment]
已经支持压测报告 markdown/html 格式。
https://github.com/link1st/go-stress-testing/releases/tag/v1.0.18
