### ISSUE TITLE
websocket  压测成功数都是0,是正确的吗

### ISSUE THREAD

**Issue by boobusy** [link1st/go-stress-testing#9]
go run main.go -c 10 -n 1 -u ws://127.0.0.1:4455/

 开始启动  并发数:10 请求数:1 请求参数:
request:
 url:ws://127.0.0.1:4455/
 form:webSocket

 method:GET
 headers:map[]
 verify:json
 timeout:3s
 debu:false

─────┬───────┬───────┬───────┬────────┬────────┬────────┬────────┬────────
 耗时│ 并发数│ 成功数│ 失败数│   qps  │最长耗时│最短耗时│平均耗时│ 错误码
─────┼───────┼───────┼───────┼────────┼────────┼────────┼────────┼────────
   1s│       0│      0│      0│     0.00│    0.00│    0.00│    0.00│
   2s│     10│      0│     10│    0.00│    2.95│    0.00│    0.00│0:10
   3s│     10│      0│     10│    0.00│    2.95│    0.00│    0.00│0:10
   4s│     10│      0│     10│    0.00│    2.95│    0.00│    0.00│0:10

**Comment by link1st** [comment]
这里并发数 从 0(1s时候) => 10(2s时候)，webSocket 是连接成功了，从错误码来看应该是验证器校验返回结果没有通过


- 调试模式查看，可以查看到返回数据是什么

```
go run main.go -c 10 -n 1 -d true -u ws://127.0.0.1:4455/
```

- 自定义 webSocket 验证器

webSocket 压测的时候在接收请求返回数据的时候会验证结果是否正确，验证函数如下文件处:

[websokcet_verify.go](https://github.com/link1st/go-stress-testing/blob/master/server/verify/websokcet_verify.go)

正确的返回数据示例:`{"seq":"1566276523281-585638","cmd":"heartbeat","response":{"code":200,"codeMsg":"Success","data":null}}`

因为各个业务不同，如果这个验证器不太合适，可以在这个函数处自行改造

```
// isSucceed 为验证是否成功，true的时候才成功数才可以+1
func WebSocketJson(request *model.Request, seq string, msg []byte) (code int, isSucceed bool)
```


- 自定义webSocket发送数据

如果需要自定义发送数据，可以修改 [websocket_link.go](https://github.com/link1st/go-stress-testing/blob/master/server/golink/websocket_link.go) 第91行位置

**Comment by boobusy** [comment]
看了代码懂了,3q
