### ISSUE TITLE
如何高效统计百万连接压测时的QPS、时延等数据

### ISSUE THREAD

**Issue by irying** [link1st/go-stress-testing#90]
看了README介绍了单机可以支持百万连接，但是分16个机器发压，是能支持统计百万连接时，服务端处理的QPS跟时延吗

**Comment by link1st** [comment]
README 中的压测是为了压测最大连接数，并未压测 QPS 所以没有百万连接下服务器的 QPS 和 延时数据
> 本工具也是支持 QPS 统计的
