### ISSUE TITLE
QPS数据突然断崖下降

### ISSUE THREAD

**Issue by binwan-dev** [link1st/go-stress-testing#92]
您好，我这边测试出现一个问题，在压测151秒左右时突然qps从3万多掉到只有几百然后缓慢上升，请问这个原因是什么导致的呀。
机器是：8核16线程 32G内存
服务器例子就是 Readme里面的例子

![image](https://user-images.githubusercontent.com/45676208/176581220-195ef3ac-837b-4e2a-bd21-ad69887de973.png)

测试命令：
go-stress-testing-linux -n 10000 -c 4000 -u http://127.0.0.1:8088
压测工具的cpu我调整到了 4

服务器端代码：
``` golang
package main
import (
    "log"
    "net/http"
    "runtime"
)

const (
    httpPort = "8088"
)

func main() {

    runtime.GOMAXPROCS(runtime.NumCPU() - 4)

    hello := func(w http.ResponseWriter, req *http.Request) {
        data := "Hello, go-stress-testing! \n"

        w.Header().Add("Server", "golang")
        w.Write([]byte(data))

        return
    }

    http.HandleFunc("/", hello)
    err := http.ListenAndServe(":"+httpPort, nil)

    if err != nil {
        log.Fatal("ListenAndServe: ", err)
    }
}

```

**Comment by link1st** [comment]
按你的设置，可能原因压测工具是 HTTPserver 相互竞争 CPU，导致 HTTPserver 无可用CPU资源，导致暂时处理请求中断，后续竞争到了 CPU 资源才慢慢恢复请求处理

**Comment by fulin87** [comment]
我也遇到了相同的问题，我觉得不是CPU竞争引起的，我是压测机和服务端分开在不同的机器，还是出现了，具体原因还在研究中
