### ISSUE TITLE
cpu 使用数应该提供一个参数让用户指定

### ISSUE THREAD

**Issue by jwrookie** [link1st/go-stress-testing#94]

**Comment by link1st** [comment]
已经添加参数，指定 CPU 核数，默认为单核
> 通常场景下单核已经够使用，设定核数过高，容易出现超时大量接口超时


https://github.com/link1st/go-stress-testing/commit/bbe53a141429416bc80f88af50ac7b82921d8ca2

**Comment by jwrookie** [comment]
oh，感谢
