### ISSUE TITLE
该压测工具在进行websocket测试的时候，对返回的格式有限制

### ISSUE THREAD

**Issue by lsm1103** [link1st/go-stress-testing#96]
该压测工具在进行websocket测试的时候，对返回的格式有限制，不是规定的格式会判定为失败；如下图，同样的服务，格式不一样

![image](https://user-images.githubusercontent.com/37491314/178649688-adb9b118-4690-4a33-947c-f0a7861b975d.png)

![image](https://user-images.githubusercontent.com/37491314/178650021-a454131d-9a5b-4b86-9115-b7eae1feb3ce.png)

**Comment by link1st** [comment]
由于 WS 协议的不同，项目只是按一种示例格式进行校验

如有不同的协议格式校验，可以修改源码的方式再进行压测
