### ISSUE TITLE
keepalive 的设计是否有问题

### ISSUE THREAD

**Issue by Hccake** [link1st/go-stress-testing#98]
看了下代码，目前开启 keepAlive 时，所有的协程使用的 httplongclinet 是同一个。

是否应该改为开启 keepAlive 时，每个协程使用不同的 httplongclinet，但是循环请求时复用此 client，否则 -c 并发数 和 -n 循环次数分开就没什么意义了。

**Comment by link1st** [comment]
并发指的是同时处理的数据的能力，按这个要求多个协程之间不应该共用一个 httpClient，关于这块后续会优化一下。

**Comment by link1st** [comment]
已经优化完成

https://github.com/link1st/go-stress-testing/pull/101/files
